name: "football"
version: "1.0.0"
config-version: 2

profile: "football"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  football:
    silver:
      +materialized: table
      +schema: SILVER
      +tags: ["silver"]

    gold:
      +materialized: table
      +schema: GOLD
      +tags: ["gold"]