-- Reference DDL for the objects managed by `python -m ingestion.cli check`.
-- Replace <DATABASE> and <SCHEMA> before running this file manually.
-- The Python bootstrap is authoritative because it also creates all 12 RAW
-- tables and their asset-specific latest-version views from config/assets.yml.

CREATE SCHEMA IF NOT EXISTS <DATABASE>.<SCHEMA>;

CREATE STAGE IF NOT EXISTS <DATABASE>.<SCHEMA>.TRANSFERMARKT_BRONZE_STAGE;

CREATE FILE FORMAT IF NOT EXISTS <DATABASE>.<SCHEMA>.TRANSFERMARKT_NDJSON_FORMAT
  TYPE = JSON
  COMPRESSION = AUTO
  STRIP_OUTER_ARRAY = FALSE;

CREATE TABLE IF NOT EXISTS <DATABASE>.<SCHEMA>.TRANSFERMARKT_INGESTION_BATCHES (
  BATCH_ID VARCHAR NOT NULL,
  MODE VARCHAR NOT NULL,
  REQUESTED_ASSETS VARIANT NOT NULL,
  STATUS VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  FINISHED_AT TIMESTAMP_TZ,
  SUMMARY VARIANT,
  ERROR VARCHAR
);

CREATE TABLE IF NOT EXISTS <DATABASE>.<SCHEMA>.TRANSFERMARKT_INGESTION_FILES (
  RUN_ID VARCHAR NOT NULL,
  BATCH_ID VARCHAR,
  ASSET VARCHAR NOT NULL,
  MODE VARCHAR NOT NULL,
  SOURCE_URL VARCHAR NOT NULL,
  SOURCE_FILE VARCHAR,
  SOURCE_FILE_SHA256 VARCHAR,
  STATUS VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  FINISHED_AT TIMESTAMP_TZ,
  ROWS_READ NUMBER,
  ROWS_LOADED NUMBER,
  OBSERVED_HEADERS VARIANT,
  SCHEMA_CHANGED BOOLEAN,
  ORIGINAL_STAGE_PATH VARCHAR,
  PREPARED_STAGE_PATH VARCHAR,
  ERROR VARCHAR
);

-- Repeated as <ASSET>_RAW by the bootstrap for every configured asset.
CREATE TABLE IF NOT EXISTS <DATABASE>.<SCHEMA>.<ASSET>_RAW (
  RAW_RECORD VARIANT NOT NULL,
  SOURCE_URL VARCHAR NOT NULL,
  SOURCE_FILE VARCHAR NOT NULL,
  SOURCE_FILE_SHA256 VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER NOT NULL,
  INGESTION_RUN_ID VARCHAR NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL
);

-- The bootstrap creates <ASSET>_LATEST by joining <ASSET>_RAW to the newest
-- SUCCESS record in TRANSFERMARKT_INGESTION_FILES. See docs/bronze_contract.md.

